version: "3.8"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/langlyai-backend:latest
    container_name: langlyai-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    image: ${DOCKERHUB_USERNAME}/langlyai-frontend:latest
    container_name: langlyai-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend